const teamList = [
  {
    id: 1,
    name: "Jatin Bhusal",
    role: "Founder and CEO",
    image: "/team/salma_tamang.jpg",
    department: "Executive",
    linkedin: " https://www.linkedin.com/in/jatin-bhusal-1012691b4/",
    googleScholar: "https://scholar.google.com/citations?user=lfW70EcAAAAJ&hl=en,%20Website:",
    researchGate: "",
    github: "",
  },
  {
    id: 2,
    name: "Salma Tamang",
    role: "Research Assistant, AI",
    image: "/team/salma_tamang.jpg",
    department: "Research",
    division: "Center for Human Mobility and Communications",
    linkedin: "https://linkedin.com/in/salma-tamang-175490269",
    googleScholar: "",
    researchGate: "https://www.researchgate.net/profile/Salma-Tamang",
    github: "",
  },
  {
    id: 3,
    name: "Dipen Boyaju",
    role: "Full Stack Developer",
    image: "",
    department: "Product Development",
    linkedin: "https://www.linkedin.com/in/dipen-boyaju-aa877124b/",
    googleScholar: "",
    researchGate: "",
    github: "https://github.com/DipenBoyaju",
  },
  {
    id: 4,
    name: "Nisha Singh Thakuri",
    role: "Management Intern",
    image: "",
    department: "Management",
    linkedin: "https://linkedin.com/in/nisha-singh-thakuri-334332311/",
    googleScholar: "",
    researchGate: "",
    github: "",
  },
  {
    id: 5,
    name: "Dr. Manish Sakhakarmy, PhD",
    role: "Research Consultant, Research Methodology",
    image: "/team/manish_sakhakarmy.jpg",
    department: "Consultants",
    linkedin: "https://linkedin.com/in/manish-sakhakarmy",
    googleScholar: "https://scholar.google.com/citations?hl=en&user=wd5q0rMAAAAJ",
    researchGate: "",
    github: "",
  },
  {
    id: 6,
    name: "Shrima Chudal",
    role: "Research Assistant, Mental Health",
    image: "/team/shrima_chudal.jpg",
    department: "Research",
    division: "Center for Cognitive and Emotional Intelligence",
    linkedin: "https://linkedin.com/in/shrimachudal",
    googleScholar: "",
    researchGate: "",
    github: "",
  },
  {
    id: 7,
    name: "Ashish Panday",
    role: "Research Intern, AI and Engineering",
    image: "",
    department: "Research",
    division: "Center for Human Mobility and Communications",
    linkedin: "",
    googleScholar: "",
    researchGate: "",
    github: "",
  },
  {
    id: 8,
    name: "Riya Acharya",
    role: "Research Consultant, AI",
    image: "",
    department: "Consultants",
    linkedin: "",
    googleScholar: "",
    researchGate: "",
    github: "",
  },
  {
    id: 9,
    name: "Prason Shakya",
    role: "DevOps",
    image: "",
    department: "Consultants",
    linkedin: "",
    googleScholar: "",
    researchGate: "",
    github: "",
  },

];

export default teamList;