const teamList = [
  {
    id: 1,
    name: "Jatin Bhusal",
    role: "Founder and CEO, Research Lead",
    image: "/images/teams/jatin_bhusal.webp",
    category: "",
    department: "Executive",
    bio: "Jatin Bhusal is an AI researcher, educator, and passionate advocate for inclusive technology. With five years of experience as an entrepreneur and certified trainer, he focuses on creating assistive solutions that enhance the lives of differently-abled individuals. Coming from a Computer Engineering background, Jatin has worked in cutting-edge fields like Computer Vision and Quantum Machine Learning. He also supports young innovators through startup mentoring, business coaching, and soft skills training—bringing people, ideas, and technology together to drive meaningful change.",
    linkedin: " https://www.linkedin.com/in/jatin-bhusal-1012691b4/",
    googleScholar: "https://scholar.google.com/citations?user=lfW70EcAAAAJ&hl=en,%20Website:",
    researchGate: "",
    github: "",
    website: "https://sites.google.com/view/jatinbhusal",
  },
  {
    id: 2,
    name: "Salma Tamang",
    role: "Research Assistant, AI",
    image: "/images/teams/salma_tamang.jpg",
    department: "Research",
    division: "Center for Human Mobility and Communications",
    linkedin: "https://linkedin.com/in/salma-tamang-175490269",
    googleScholar: "",
    researchGate: "https://www.researchgate.net/profile/Salma-Tamang",
    github: "",
    bio: "I am Salma Tamang, an Information Technology graduate from Nepal College of Information Technology. My core expertise lies in deep learning, computer vision, and natural language processing. I’ve also gained valuable experience through advanced training programs like the 5th Annual Nepal AI School and a hands-on AI internship at AMNIL Technology and currently working as ML engineer at PalmMind Technology."
  },
  {
    id: 3,
    name: "Dipen Boyaju",
    role: "Full Stack Developer",
    image: "/images/teams/dipen_boyaju.webp",
    department: "Product Development",
    linkedin: "https://www.linkedin.com/in/dipen-boyaju-aa877124b/",
    googleScholar: "",
    researchGate: "",
    github: "https://github.com/DipenBoyaju",
    website: "https://dipenboyaju.com.np/",
  },
  {
    id: 4,
    name: "Nisha Singh Thakuri",
    role: "Management Intern",
    image: "/images/teams/nisha_singh_thakuri.jpg",
    department: "Management",
    linkedin: "https://linkedin.com/in/nisha-singh-thakuri-334332311/",
    googleScholar: "",
    researchGate: "",
    github: "",
  },
  {
    id: 5,
    name: "Dr. Manish Sakhakarmy, PhD",
    role: "Research Consultant, Research Methodology",
    image: "/images/teams/manish_sakhakarmy.jpg",
    department: "Consultants",
    linkedin: "https://linkedin.com/in/manish-sakhakarmy",
    googleScholar: "https://scholar.google.com/citations?hl=en&user=wd5q0rMAAAAJ",
    researchGate: "",
    github: "",
  },
  {
    id: 6,
    name: "Shrima Chudal",
    role: "Research Assistant, Mental Health",
    image: "/images/teams/shrima_chudal.webp",
    department: "Research",
    division: "Center for Cognitive and Emotional Intelligence",
    linkedin: "https://linkedin.com/in/shrimachudal",
    googleScholar: "",
    researchGate: "",
    github: "",
  },
  {
    id: 7,
    name: "Ashish Panday",
    role: "Research Intern, AI and Engineering",
    image: "/images/teams/Ashish_Panday.jpg",
    department: "Research",
    division: "Center for Human Mobility and Communications",
    linkedin: "",
    googleScholar: "",
    researchGate: "",
    github: "https://github.com/mr-ashish-panday",
  },
  {
    id: 8,
    name: "Riya Acharya",
    role: "Research Consultant, AI",
    image: "/images/teams/Riya_Acharya.jpg",
    department: "Consultants",
    bio: "Riya Acharya is currently pursuing her Master of Technology in Artificial Intelligence at Kathmandu University. She serves as an Industry Training Associate at NAAMII, where she designs AI pedagogy and supports students and professionals in developing the expertise needed to thrive in a rapidly evolving technological landscape. Riya is also the co-founder of STEMinist Nepal, a campaign dedicated to increasing the representation of young women in STEM fields. Her research interests lie in Natural Language Processing (NLP) and Large Language Models (LLMs), where she is passionate about driving innovation and contributing meaningful advancements to the field.",
    linkedin: "https://www.linkedin.com/in/riya-acharya/",
    googleScholar: "",
    researchGate: "",
    github: "",
  },
  {
    id: 9,
    name: "Prason Shakya",
    role: "DevOps",
    image: "/images/teams/Prason_Pandey.png",
    department: "Consultants",
    linkedin: "https://linkedin.com/in/itsprason",
    googleScholar: "",
    researchGate: "",
    github: "",
  },

];

export default teamList;